import time
import os
slide1='                                       $$$$$$$$'
slide2='                                 $$$$$$$$$$$$$$$$$$'
slide3='                              $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
slide4='                          $$$$$$$$$$$$$$$$ $      $$$$$$$$$$$$$$$$$$$'
slide5='                        $$$$$$$$$$$               $$ $$$$$$$$$$$$$$$$$$'
slide6='                       $$$$$$$$ $$$                    $$$$$$$$$$$$$$$$$'
slide7='             $$$$$$$  $$$$$$$                   $$$$$  $$$$$$$$$$$$$$$$$$'
slide8='         $$$$$$$$$$$$$$$$$$$        $          $$$$$$$  $$$$$$$$$$$$$$$$$'
slide9='       $$$$$$$$$$$$$$$$$$$$      $$$$$$$       $$$$$$$  $$$$$$$$$$$$$$$$$$'
slide10='     $$$$$$$$$$$$$$$$$$$$$$     $$$$$$$$        $$$$$   $$$$$$$$$$$$$$$$$$'
slide11='    $$$$$$$$$$$$$$$$$$$$$$$      $$$$$$$     $$$        $$$$$$$$$$$$$$$$$$'
slide12='   $$$$$$$$$$$$$$$$$$$$$$$$$        $                  $$$$$$$$$$$$$$$$$$' 
slide13='  $$$$$$$$$$$$$$$$$$$$$$$$$$                   $      $$$$$$$$$$$$$$$$$$'
slide14=' $$$$$$$$$$$$$$$$$$$$$$$$$$$$$                      $$$$$$$$$$$$$$$$$$'
slide15=' $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$            $$$$$ $$$$$$$$$$$$$$$$$$$'
slide16='  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
slide17='   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $$$$$$$$$$$$$$$$'
slide18='   $$$$$$$$$$$$$$$$$$$$$$$$$$ $$ $$ $  $$$$$$$$$$$$$$$$$$$$$'
slide19='    $$$$$$$$$$$$$$$$$$$$$$$$$   $ $$$$$$$    $$ $$$$$$$$$$$$'
slide20='     $$$$$$$$$$$$$$$$$$$$$   $$$$$$$$      $ $$$$$$$$$$$$$$'
slide21='        $$$$$$$$$$$$$$$     $$$$$$$$$$    $  $$$$$ $$$$$$$'
slide22='              $$$          $$$$ $$$$  $$ $ $$$$$ $$$$$'
slide23='                            $$$$ $$$  $   $ $$ $$$$ $$'
slide24='                            $$$$$$$     $ $ $$$$$$$$$$$'
slide25='                             $$$$$$ $$$  $ $$$$$$$$$$$$'
slide26='                               $$$$$$$$$$$$$$$$$$$$$$$'
slide27='                                $$$$$$$$$$$$$$$$$$$$$$'
slide28='                              $$$$$$$$$$$$$$$$$$$$$ $$$$'
slide29='                            $$$$$$$$$$$$$$$$ $$$$$$$$$$$$'
slide30='                           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
slide31='                           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'

slide32='                                       $$$$$$$$'
slide33='                                $$$$$$$$$$$$$$$$$$'
slide34='                             $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
slide35='                          $$$$$$$$$$$$$$$$ $      $$$$$$$$$$$$$$$$$$$'
slide36='                        $$$$$$$$$$$               $$ $$$$$$$$$$$$$$$$$$'
slide37='                       $$$$$$$$ $$$                    $$$$$$$$$$$$$$$$$'
slide38='                   $  $$$$$$$                   $$$$$  $$$$$$$$$$$$$$$$$$'
slide39='               $$$$$$$$$$$$$                   $$$$$$$  $$$$$$$$$$$$$$$$$'
slide40='             $$$$$$$$$$$$$$    $$$$$$$$        $$$$$$$  $$$$$$$$$$$$$$$$$$'
slide41='           $$$$$$$$$$$$$$$$     $$$$$$$$        $$$$$   $$$$$$$$$$$$$$$$$$'
slide42='          $$$$$$$$$$$$$$$$$                             $$$$$$$$$$$$$$$$$$'
slide43='         $$$$$$$$$$$$$$$$$$$       $$                  $$$$$$$$$$$$$$$$$$'
slide44='        $$$$$$$$$$$$$$$$$$$$         $$$              $$$$$$$$$$$$$$$$$$' 
slide45='       $$$$$$$$$$$$$$$$$$$$$$$          $$$$$$      $$$$$$$$$$$$$$$$$$'
slide46='       $$$$$$$$$$$$$$$$$$$$$$$$$                  $$$$$$$$$$$$$$$$$$$'
slide47='        $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
slide48='        $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $$$$$$$$$$$$$$$$'
slide49='         $$$$$$$$$$$$$$$$$$$$ $$ $$ $  $$$$$$$$$$$$$$$$$$$$$'
slide50='          $$$$$$$$$$$$$$$$$$$   $ $$$$$$$    $$ $$$$$$$$$$$$'
slide51='           $$$$$$$$$$$$$$$   $$$$$$$$      $ $$$$$$$$$$$$$$'
slide52='              $$$$$$$$$     $$$$$$$$$$    $  $$$$$ $$$$$$$'
slide53='                    $$$    $$$$ $$$$  $$ $ $$$$$ $$$$$'
slide54='                            $$$$ $$$  $   $ $$ $$$$ $$'
slide55='                            $$$$$$$     $ $ $$$$$$$$$$$'
slide56='                             $$$$$$ $$$  $ $$$$$$$$$$$$'
slide57='                               $$$$$$$$$$$$$$$$$$$$$$$'
slide58='                                $$$$$$$$$$$$$$$$$$$$$$'
slide59='                              $$$$$$$$$$$$$$$$$$$$$ $$$$'
slide60='                            $$$$$$$$$$$$$$$$ $$$$$$$$$$$$'
slide61='                           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
slide62='                           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$' 
print(slide1)                           
print(slide2)
print(slide3)
print(slide4)                           
print(slide5)
print(slide6)
print(slide7)                           
print(slide8)
print(slide9)
print(slide10)                           
print(slide11)
print(slide12)
print(slide13)                           
print(slide14)
print(slide15)
print(slide16)                           
print(slide17)
print(slide18)
print(slide19)                           
print(slide20)
print(slide21)
print(slide22)                           
print(slide23)
print(slide24)
print(slide25)                           
print(slide26)
print(slide27)
print(slide28)                           
print(slide29)
print(slide30)
print(slide31)                           
print(slide32)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide33)                           
print(slide34)
print(slide35)
print(slide36)                           
print(slide37)
print(slide38)
print(slide39)                           
print(slide40)
print(slide41)
print(slide42)                           
print(slide43)
print(slide44)
print(slide45)                           
print(slide46)
print(slide47)
print(slide48)                           
print(slide49)
print(slide50)
print(slide51)                           
print(slide52)
print(slide53)
print(slide54)                           
print(slide55)
print(slide56)
print(slide57)                           
print(slide58)
print(slide59)
print(slide60)                           
print(slide61)
print(slide62)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide1)                           
print(slide2)
print(slide3)
print(slide4)                           
print(slide5)
print(slide6)
print(slide7)                           
print(slide8)
print(slide9)
print(slide10)                           
print(slide11)
print(slide12)
print(slide13)                           
print(slide14)
print(slide15)
print(slide16)                           
print(slide17)
print(slide18)
print(slide19)                           
print(slide20)
print(slide21)
print(slide22)                           
print(slide23)
print(slide24)
print(slide25)                           
print(slide26)
print(slide27)
print(slide28)                           
print(slide29)
print(slide30)
print(slide31)                           
print(slide32)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide33)                           
print(slide34)
print(slide35)
print(slide36)                           
print(slide37)
print(slide38)
print(slide39)                           
print(slide40)
print(slide41)
print(slide42)                           
print(slide43)
print(slide44)
print(slide45)                           
print(slide46)
print(slide47)
print(slide48)                           
print(slide49)
print(slide50)
print(slide51)                           
print(slide52)
print(slide53)
print(slide54)                           
print(slide55)
print(slide56)
print(slide57)                           
print(slide58)
print(slide59)
print(slide60)                           
print(slide61)
print(slide62)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide1)                           
print(slide2)
print(slide3)
print(slide4)                           
print(slide5)
print(slide6)
print(slide7)                           
print(slide8)
print(slide9)
print(slide10)                           
print(slide11)
print(slide12)
print(slide13)                           
print(slide14)
print(slide15)
print(slide16)                           
print(slide17)
print(slide18)
print(slide19)                           
print(slide20)
print(slide21)
print(slide22)                           
print(slide23)
print(slide24)
print(slide25)                           
print(slide26)
print(slide27)
print(slide28)                           
print(slide29)
print(slide30)
print(slide31)                           
print(slide32)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide33)                           
print(slide34)
print(slide35)
print(slide36)                           
print(slide37)
print(slide38)
print(slide39)                           
print(slide40)
print(slide41)
print(slide42)                           
print(slide43)
print(slide44)
print(slide45)                           
print(slide46)
print(slide47)
print(slide48)                           
print(slide49)
print(slide50)
print(slide51)                           
print(slide52)
print(slide53)
print(slide54)                           
print(slide55)
print(slide56)
print(slide57)                           
print(slide58)
print(slide59)
print(slide60)                           
print(slide61)
print(slide62)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide1)                           
print(slide2)
print(slide3)
print(slide4)                           
print(slide5)
print(slide6)
print(slide7)                           
print(slide8)
print(slide9)
print(slide10)                           
print(slide11)
print(slide12)
print(slide13)                           
print(slide14)
print(slide15)
print(slide16)                           
print(slide17)
print(slide18)
print(slide19)                           
print(slide20)
print(slide21)
print(slide22)                           
print(slide23)
print(slide24)
print(slide25)                           
print(slide26)
print(slide27)
print(slide28)                           
print(slide29)
print(slide30)
print(slide31)                           
print(slide32)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide33)                           
print(slide34)
print(slide35)
print(slide36)                           
print(slide37)
print(slide38)
print(slide39)                           
print(slide40)
print(slide41)
print(slide42)                           
print(slide43)
print(slide44)
print(slide45)                           
print(slide46)
print(slide47)
print(slide48)                           
print(slide49)
print(slide50)
print(slide51)                           
print(slide52)
print(slide53)
print(slide54)                           
print(slide55)
print(slide56)
print(slide57)                           
print(slide58)
print(slide59)
print(slide60)                           
print(slide61)
print(slide62)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide1)                           
print(slide2)
print(slide3)
print(slide4)                           
print(slide5)
print(slide6)
print(slide7)                           
print(slide8)
print(slide9)
print(slide10)                           
print(slide11)
print(slide12)
print(slide13)                           
print(slide14)
print(slide15)
print(slide16)                           
print(slide17)
print(slide18)
print(slide19)                           
print(slide20)
print(slide21)
print(slide22)                           
print(slide23)
print(slide24)
print(slide25)                           
print(slide26)
print(slide27)
print(slide28)                           
print(slide29)
print(slide30)
print(slide31)                           
print(slide32)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide33)                           
print(slide34)
print(slide35)
print(slide36)                           
print(slide37)
print(slide38)
print(slide39)                           
print(slide40)
print(slide41)
print(slide42)                           
print(slide43)
print(slide44)
print(slide45)                           
print(slide46)
print(slide47)
print(slide48)                           
print(slide49)
print(slide50)
print(slide51)                           
print(slide52)
print(slide53)
print(slide54)                           
print(slide55)
print(slide56)
print(slide57)                           
print(slide58)
print(slide59)
print(slide60)                           
print(slide61)
print(slide62)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide1)                           
print(slide2)
print(slide3)
print(slide4)                           
print(slide5)
print(slide6)
print(slide7)                           
print(slide8)
print(slide9)
print(slide10)                           
print(slide11)
print(slide12)
print(slide13)                           
print(slide14)
print(slide15)
print(slide16)                           
print(slide17)
print(slide18)
print(slide19)                           
print(slide20)
print(slide21)
print(slide22)                           
print(slide23)
print(slide24)
print(slide25)                           
print(slide26)
print(slide27)
print(slide28)                           
print(slide29)
print(slide30)
print(slide31)                           
print(slide32)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide33)                           
print(slide34)
print(slide35)
print(slide36)                           
print(slide37)
print(slide38)
print(slide39)                           
print(slide40)
print(slide41)
print(slide42)                           
print(slide43)
print(slide44)
print(slide45)                           
print(slide46)
print(slide47)
print(slide48)                           
print(slide49)
print(slide50)
print(slide51)                           
print(slide52)
print(slide53)
print(slide54)                           
print(slide55)
print(slide56)
print(slide57)                           
print(slide58)
print(slide59)
print(slide60)                           
print(slide61)
print(slide62)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide1)                           
print(slide2)
print(slide3)
print(slide4)                           
print(slide5)
print(slide6)
print(slide7)                           
print(slide8)
print(slide9)
print(slide10)                           
print(slide11)
print(slide12)
print(slide13)                           
print(slide14)
print(slide15)
print(slide16)                           
print(slide17)
print(slide18)
print(slide19)                           
print(slide20)
print(slide21)
print(slide22)                           
print(slide23)
print(slide24)
print(slide25)                           
print(slide26)
print(slide27)
print(slide28)                           
print(slide29)
print(slide30)
print(slide31)                           
print(slide32)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide33)                           
print(slide34)
print(slide35)
print(slide36)                           
print(slide37)
print(slide38)
print(slide39)                           
print(slide40)
print(slide41)
print(slide42)                           
print(slide43)
print(slide44)
print(slide45)                           
print(slide46)
print(slide47)
print(slide48)                           
print(slide49)
print(slide50)
print(slide51)                           
print(slide52)
print(slide53)
print(slide54)                           
print(slide55)
print(slide56)
print(slide57)                           
print(slide58)
print(slide59)
print(slide60)                           
print(slide61)
print(slide62)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide1)                           
print(slide2)
print(slide3)
print(slide4)                           
print(slide5)
print(slide6)
print(slide7)                           
print(slide8)
print(slide9)
print(slide10)                           
print(slide11)
print(slide12)
print(slide13)                           
print(slide14)
print(slide15)
print(slide16)                           
print(slide17)
print(slide18)
print(slide19)                           
print(slide20)
print(slide21)
print(slide22)                           
print(slide23)
print(slide24)
print(slide25)                           
print(slide26)
print(slide27)
print(slide28)                           
print(slide29)
print(slide30)
print(slide31)                           
print(slide32)
#print(end='\r')
time.sleep(1)
os.system('cls')
print(slide33)                           
print(slide34)
print(slide35)
print(slide36)                           
print(slide37)
print(slide38)
print(slide39)                           
print(slide40)
print(slide41)
print(slide42)                           
print(slide43)
print(slide44)
print(slide45)                           
print(slide46)
print(slide47)
print(slide48)                           
print(slide49)
print(slide50)
print(slide51)                           
print(slide52)
print(slide53)
print(slide54)                           
print(slide55)
print(slide56)
print(slide57)                           
print(slide58)
print(slide59)
print(slide60)                           
print(slide61)
print(slide62)